name: CI

on: [push]
env:
  CI: "true"

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn lint
    - run: yarn test
    - run: yarn build

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: ['validate']
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
        registry-url: https://registry.npmjs.org/
    - name: Setup Git
      run: |
        git config --local user.email "dev@zelzen.io"
        git config --local user.name "Zelzen Bot"
        git checkout -B master
    - run: yarn install
    - run: yarn build
    - run: yarn release
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        # github_token: ${{ secrets.GH_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
